apiVersion: apps/v1
kind: Deployment
metadata:
  name: atolye15
  namespace: default
  labels:
    app: atolye15
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atolye15
  template:
    metadata:
      labels:
        app: atolye15
    spec:
      containers:
        - name: atolye15
          image: enderpiyale/atolye15:stage
          ports:
            - containerPort: 80
              name: http