apiVersion: v1
kind: Service
metadata:
  name: atolye15
  namespace: default
  labels:
    app: atolye15
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    app: atolye15